project_id = "qifcynwnxmtoxzpskmmt"

[functions.yemot-callback]
verify_jwt = false

[functions.process-overdue-calls]
verify_jwt = false

[functions.sim-activation-request]
verify_jwt = false

[functions.sim-activation-callback]
verify_jwt = false

[functions.cellstation-api]
verify_jwt = false
